### ISSUE TITLE
Created a new class for hadling exceptions and write logs

### ISSUE THREAD

**Issue by bot8080** [python/exceptiongroups#10]
I have created a small class to handle the exceptions easily and creating a log file respectively. I want to submit this small piece of code. How can I ?

**Comment by gvanrossum** [comment]
Is your contribution for this particular project? In this repo we are experimenting with a design for multi-errors as found in Trio.

**Comment by bot8080** [comment]
Actually, it is a small 10-20 lines of code only. I created a normal class in order to track exceptions and create a log file corresponding to it. I want to request you, if you can add this library into official python3 repo. It will be helpful for a new/old user to learn and track exceptions quickly. Here is demo 

Try:
    Print(dict)
Except:
    Error = handleException()
    Error.createlog('filename.txt','extra comment line can also be added into file if neede sometimes ')

# comment is optional 
Details like line number, file name, exception type or name will be written into file.

**Comment by gvanrossum** [comment]
I think you got the wrong tracker. Try mailing python-ideas.

**Comment by bot8080** [comment]
Sir, how can i contact there. Is it any repository name??

**Comment by gvanrossum** [comment]
It's a mailing list. Just Google it.
