### ISSUE TITLE
Use cases for ExceptionGroups

### ISSUE THREAD

**Issue by iritkatriel** [python/exceptiongroups#11]
I came across https://bugs.python.org/issue29980  and wanted a place to save it, hence this issue.

**Comment by gvanrossum** [comment]
You can also add yourself to the nosy list.

**Comment by iritkatriel** [comment]
Another one: https://bugs.python.org/issue40857

Here the ArithmeticError is not really related to the FileNotFoundError, so perhaps tempfile.TemporaryDirectory() should raise them both in an ExceptionGroup so the user has to deal with both.

(Note that the fix was to not raise the FileNotFoundError at all, so the issue was sidestepped).

**Comment by 1st1** [comment]
> I came across https://bugs.python.org/issue29980 and wanted a place to save it, hence this issue.

That's an interesting and good use case.

**Comment by bluetech** [comment]
*Not sure if you mean to solicit external comments, I found this repo through a trio backlink*

We have a use case for an ExceptionGroup concept in pytest, wrote it up briefly here: https://github.com/pytest-dev/pytest/issues/8217

Similar situation with finalizers also exists in [pluggy](https://github.com/pytest-dev/pluggy) (a library that pytest, tox and others use for implementing "hooks") but I haven't written it up.

**Comment by iritkatriel** [comment]
Thank you @bluetech, that's a useful contribution.

**Comment by Zac-HD** [comment]
I'm also keen to use it in Hypothesis - we ([optionally](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.report_multiple_bugs)) [report multiple bugs](https://hypothesis.works/articles/multi-bug-discovery/), including where [a single exception can have multiple causes](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-1-0).

Currently we have to [print the inner tracebacks](https://github.com/HypothesisWorks/hypothesis/blob/de4b6f2961cc043391e3a5728c2d999bca2470cd/hypothesis-python/src/hypothesis/core.py#L1089-L1102), which is pretty bad for [runtime usecases](https://stackoverflow.com/a/65713239/9297601).  It's *usually* OK for test runners like pytest, unittest, or Django, but assuming they end up ExceptionGroup-aware I'd expect that to work better.

**Comment by iritkatriel** [comment]
Thank you @Zac-HD, that's an interesting use case and not quite the same as the pytest one.

**Comment by iritkatriel** [comment]
These have all been added to the draft.
