### ISSUE TITLE
What should else do on a try-except*?

### ISSUE THREAD

**Issue by iritkatriel** [python/exceptiongroups#12]
I think we haven't defined the semantics of else on except* yet.

```
try:
   <code>
except* ValueError as e:
   <code>
except* TypeError as e:
   <code>
else:
   <code>

```
The else block executes when no except* clause matches? 

I never used else on except. What do people do with it?

**Comment by gvanrossum** [comment]
No, it’s only for the case where nothing was raised at all. It’s to put code that is run on success but where exceptions shouldn’t be caught (so you can’t just put it at the end of the try clause).

**Comment by iritkatriel** [comment]
Ah, then that's easy, it's exactly the same as with except.
