### ISSUE TITLE
Finish the PEP

### ISSUE THREAD

**Issue by iritkatriel** [python/exceptiongroups#22]
This is a space to discuss anything else that we still need to do.

**Comment by iritkatriel** [comment]
1. Convert to .rst
2. Write missing sections (or remove the headings):  "Security Implications", "How to Teach This", "References"

**Comment by Zac-HD** [comment]
> * Write missing sections (or remove the headings):  "Security Implications", "How to Teach This", "References"

IMO the "How to Teach This" and "References" sections are particularly important for this kind of language change.

> * Decide on the title. How about "Exception Groups" ?

"Exception Groups and `except*`"?

**Comment by 1st1** [comment]
> "Security Implications"

Are there any? There's no existing code that would suddenly become insecure with exception groups. As for the new code that would be written with the new syntax -- idk, usually we don't cover that in PEPs.

**Comment by iritkatriel** [comment]
Another use case, similar to the pytest finalizers situation: atexit currently raises the last exception any registered handler raises: https://docs.python.org/3/library/atexit.html#atexit.register

**Comment by gvanrossum** [comment]
It's beginning to look like this really has a lot of use cases!
