### ISSUE TITLE
The draft PEP does not address subclassing `ExceptionGroup`

### ISSUE THREAD

**Issue by Zac-HD** [python/exceptiongroups#24]
...and it would be helpful to have an explicit statement that this either is or is not supported.  Personally I'd lean towards unsupported, as I can't see a use-case valuable enough to justify the extra complexity when e.g. re-raising parts of an `ExceptionGroup` subclass.

**Comment by 1st1** [comment]
I have similar thoughts on this. I'd prohibit subclassing at least in 3.10, until we see there's a good case for allowing it.

**Comment by iritkatriel** [comment]
We had it in an earlier draft, I must have dropped it in one of the edits.

I'm not sure how we could allow subclassing and support split().
